sudo: false
cache: bundler
language: ruby

before_install:
  - gem update bundler

rvm:
  - 2.3.1
  - 2.2.4
  - 2.2.2
  - ruby
  - ruby-head
  - jruby-9.1.5.0
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2
  - rbx-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: jruby-9.0.5.0
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-head

notifications:
  email:
    recipients:
      - johncwang@gmail.com
    on_success: always
    on_failure: always
  webhooks:
    secure: "VGQQogkGwKHh+QWHfsbHjzwsUWKCmeoY9bNE5eTj57hNNiXmIu86UdeY9fvKY9jKDtYuz0dHKR7cPmQRF1/GS43ofIL7QmanV6GaIhzvJMXCak7wWtIrWNGeWK8qM1yhRcD8HXEjYKQloGiwBwIvh5xeO/Cy53p1uCVJ4JeCDPTdqVSFGp6qXqxF4dhBbr1Dy1i+3G/e9Gu/NHw9gghBNA6mvI2TbvXtxpstm78EEKlotgC6qbOtYAniWr8vTHEnHtF0JUQ8MbfQiuOQ3R2Z5cwGfi87xcn6a2i6atHzpCMwArQ6cAfmGRsD+5B/lK/KD5LMJnKAvqYUKzOBQhkJy19ET8B8tFhKPHz3baePUSeo98be5Q4+i0fhtuR64ONxqynqluQTcKyp1ymT8bQd0MciPJngfRIJoAsrkrvYrPv3ZqFrUJTliyy7jt33GDT0yN4gJsyJFkvlG1EwNzKWI4mjI61OzfkZ2vNPI5MoCAm88xdoNvN4To152dYCMrKak8pPa7gnVpotBGOUf3BkErfWc1t5KRx1uvU9sHzNYabMax9NKZRnSgdxyVSdMUkc2NGvp4CUbN4PcpYL7sqStnbpPMgE8jued9XpgwTJxpCwKhGHTI0IqOWxluD09JG7qLJquyQkmCgb+UmU3eT6BcY4Cz0z5v/Xo8qEO6wv1WI="

